osx_image: xcode8.3
sudo: required
dist: trusty
language: node_js

node_js:
- 10

matrix:
  include:
  - os: windows
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang

cache:
  directories:
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils rpm fakeroot; fi

install:
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then nvm install 8; fi
- source ~/.bashrc
- npm install -g xvfb-maybe
- npm i
- cd electron
- npm i
- cd ..

script:
- npm run build
- cd electron
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run make; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run publish; fi

branches:
  only:
  - master
  
