osx_image: xcode8.3
sudo: required
dist: trusty
language: c

matrix:
  include:
  - windows
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang

cache:
  directories:
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils rpm fakeroot; fi

install:
- nvm install 8
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn :init

script:
- yarn build
- cd electron
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn make; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn run publish; fi

branches:
  only:
  - master
  
