language: node_js

node_js:
- 8

matrix:
  include:
  - os: windows
  - os: osx
  - os: linux

install:
- yarn :init

script:
- npm run build
- cd electron
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn make; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn run publish; fi

branches:
  only:
  - master
  
