version: '{build}'

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - yarn :init

build_script:
  - yarn build
  - cd electron
  - IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (yarn run publish) ELSE (yarn run make)

test: off
