version: '{build}'

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64
  - x86

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'
  - electron/node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - choco install yarn --ignore-dependencies
  - git reset --hard HEAD
  - yarn :init

build_script:
  - yarn build
  - cd electron
  - yarn run publish

test: off
