version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - phpmyadmin
    restart: always
    volumes:
      - /ec/vhosts:/var/www/vhosts
      - /ec/https:/var/lib/https-portal
    environment:
      DOMAINS: 'ticket.ec-api.de -> http://ticket:80, db.ec-api.de -> http://phpmyadmin:80, git.ec-api.de -> http://git:3000, app.ec-api.de, anmeldung.ec-api.de, dev.app.ec-api.de, dev.anmeldung.ec-api.de'
      STAGE: 'production'
      # FORCE_RENEW: 'true'

  db:
    image: mariadb
    volumes:
      - /ec/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '<a>'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

  git:
    image: gitea/gitea:1.7.1
    volumes:
      - /ec/git:/data
    ports:
      - "2222:22"
    restart: always

  ticket:
    image: kanboard/kanboard:latest
    restart: always
    volumes:
      - /ec/kb-data:/var/www/app/data
      - /ec/kb-plugins:/var/www/app/plugins