version: '3'
services:
   app_master:
      image: httpd:alpine
      volumes:
         - ./packages/app/dist:/usr/local/apache2/htdocs

   https-portal:
      image: steveltn/https-portal
      ports:
         - 80:80
         - 443:443
      restart: always
      environment:
         DOMAINS: '
            app.ec-api.de -> http://app_master:80
         '
         STAGE: 'production'
