version: '3'
services:
   https-portal:
      image: steveltn/https-portal
      ports:
         - 80:80
         - 443:443
      restart: always
      environment:
         DOMAINS: '
            app.ec-api.de -> http://app_master:80,
            api.ec-api.de -> http://api_master:80
         '
         STAGE: 'production'
      networks:
         - net
networks:
  net:
    driver: bridge